ip: 10.4.44.4
token: 'BAAcdW9CQ0ZLeG4xZk1XQkN2U1N5Q3M2WXI3d0JzPQMAjAQASHVybjpzdG9yYWdlb3M6VmlydHVhbERhdGFDZW50ZXJEYXRhOmM2ZjZmY2JjLWUwNDUtNDJlZC1hZDlmLWY2NTBjNTViMzM3NgIADTE1MTQ5NDg4MjQ4NjADAC51cm46VG9rZW46MDJmNTM3NzgtMjQzYy00ZmNiLWJlNmMtNzA1ZjE0OTAxNzA0AgAC0A8='
storagepool: 'urn:storageos:VirtualArray:36453c8c-6927-4729-916d-dbdcf93885b4'
replgroup: 'urn:storageos:ReplicationGroupInfo:8d618c50-9bb5-4d2c-98f3-54537dd81666:global'
